language: r
cache: packages
pandoc_version: 1.19.2.1
before_cache: Rscript -e 'remotes::install_cran("bookdown")'

script: Rscript -e 'cat("nothing")'
after_success:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
# - touch _book/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _book
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
